version: "3"

services:
  caddy:
    image: caddy:2-alpine
    volumes:
      - /data
      - ./caddy:/etc/caddy
      - front-dist:/srv/www/front
    ports:
      - "${PORT}:80"

  backend:
    build:
      context: server
    environment:
      PORT: 10080

  frontend:
    build:
      context: frontend
    volumes:
      - front-dist:/app/dist

volumes:
  front-dist:
